config/routes.rb
RedditClone::Application.routes.draw do

  resources :users, :subs, :links
  resource :session

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :parent_comment_id, :link_id, :linnie
  # belongs_to(:comments, :foreign_key => :parent_comment_id)
#  has_many(:comments, :foreign_key => :parent_comment_id)

  has_many :sub_comments, :class_name => "Comment",
    :foreign_key => "parent_comment_id"
  belongs_to :parent_comment, :class_name => "Comment"

  belongs_to :link, :class_name => "Link", :foreign_key => "link_id"


end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url, :user_id, :link_sub_id, :content, :subs

  belongs_to(:user)

  has_many(:link_subs)

  has_many(:subs, through: :link_subs)

  has_many :comments, :foreign_key => :link_id, :class_name => "Comment"

  def comments_by_parent_id
    comment_hash = {}
    self.comments.each do |comment_child|
      self.comments.each do |comment_parent|
        if comment_child.parent_id == comment_parent.id
          comment_hash[comment_child.id] += comment_parent #pew pew pew
        end
      end
    end
  end

end

app/models/link_sub.rb
class LinkSub < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to(:link)
  belongs_to(:sub)
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :moderator_id, :name

  belongs_to(:moderator, :class_name => "User", :foreign_key => :moderator_id, :primary_key => :id)

  has_many(:link_subs)

  has_many :links, through: :link_subs
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :user_name, :password_digest, :session_token, :password
  validates :user_name, :password_digest, :session_token, presence: true


  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password
    nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def new
    render :new
  end

  def create
    params[:link][:user_id] = current_user.id
    sub_ids = params[:link][:subs]
    params[:link].delete(:subs)
    @link = Link.new(params[:link])

    sub_ids.each do |sub_id|
      @link.subs << Sub.find(sub_id)
    end

    if @link.save
      redirect_to link_url(@link)
    else
      render :new
    end
  end

  def show
    @link = Link.find(params[:id])

    render :show
  end

  def edit
    @link = Link.find(params[:id])

    render :edit
  end

  def update
    @link = Link.find(params[:id])
    if current_user.id != @link.moderator_id
      render text: "No."
    elsif @link.update_attributes(params[:link])
      redirect_to link_url(@link)
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_user_name(params[:user][:user_name])

    if @user.nil? || !@user.is_password?(params[:user][:password])
      render :new
    else
      @user.reset_session_token!
      session[:token] = @user.session_token
      redirect_to user_url(@user)
    end
  end


  def destroy
    session[:token] = nil
    render :new
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def new
    render :new
  end

  def create
    params[:sub][:moderator_id] = current_user.id

    @sub = Sub.new(params[:sub])

    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])

    render :show
  end

  def edit
    @sub = Sub.find(params[:id])

    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if current_user.id != @sub.moderator_id
      render text: "No."
    elsif @sub.update_attributes(params[:sub])
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end

  #

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.new(params[:user])
    @user.reset_session_token!

    if @user.save
      session[:token] = @user.session_token
      redirect_to user_url(@user)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:token])
  end

  def logged_in?
    !!!current_user.nil?
  end

end

app/helpers/sub_helper.rb
module SubHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if logged_in? %>
	<%= current_user.user_name %>
	<%= button_to "Log Out", session_url, method: :delete %>

	<% end %>

<%= yield %>

</body>
</html>

app/views/links/new.html.erb
<h2>Create Link</h2>
<form action="<%= links_url %>" method="post">

  <label for="link_title">Title: </label>
  <input name="link[title]" id="link_title" type="text" value="">
  <br>

  <label for="link_url">URL: </label>
  <input name="link[url]" id="link_url" type="text" value="">
  <br>

  <label for="link_content">Content: </label>
  <input name="link[content]" id="link_content" type="text" value="">
  <br>

	<% Sub.all.each do |sub| %>
	  <input type="checkbox"
		name="link[subs][]"
		id="<%="link_subs_#{sub.name}"%>"
		value="<%= sub.id %>"
		>

	  <label for="<%="link_subs_#{sub.name}"%>"> <%="link_subs_#{sub.name}"%></label>
	  <br>
	<% end %>


  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="submit" value="Crate link">
</form>

app/views/links/show.html.erb
<h2><%= @link.title %></h2>

Link URL <%= @link.url %>
<br>
Link Content <%= @link.content %>
<br>
User <%= User.find(@link.user_id).user_name %>
<br>
Link subs <% @link.subs.each do |sub| %>
	<li><%= sub.name %></li>
<% end %>

app/views/subs/edit.html.erb
<h2>Edit Sub</h2>
<form action="<%= sub_url(@sub) %>" method="post">
	<input type="hidden" name="_method" value="put">

  <label for="sub_name">Sub Name: </label>

  <input name="sub[name]" id="sub_name" type="text" value="<%= @sub.name %>">
  <br>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="submit" value="Make Changes">
</form>

app/views/subs/new.html.erb
<h2>Create Sub</h2>
<form action="<%= subs_url %>" method="post">

  <label for="sub_name">Sub Name: </label>

  <input name="sub[name]" id="sub_name" type="text" value="">
  <br>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="submit" value="Register">
</form>

app/views/subs/show.html.erb
<h1>Welcome to the <%= @sub.name%> sub!!!!</h1>

<% if current_user.id == @sub.moderator_id %>
	<%= link_to "Edit", edit_sub_url(@sub)%>
<% end %>

app/views/users/new.html.erb
<h2>Create New User</h2>
<form action="/users" method="post">
        <input name="_method" type="hidden" value="" />

  <label for="user_user_name">Username: </label>

  <input name="user[user_name]" id="user_user_name" type="text" value="">
  <br>

  <label for="user_password">Password: </label>
  <input name="user[password]" id="user_password" type="text" value="">
  <br>


  <input type="submit" value="Register">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>